/* StatusOS v2.8.0 Streamlined Artist OS */
(function () {
  "use strict";
  let selectedArtistId = window.StatusOS?.Workspace?.getSelectedArtist?.() || null;
  const esc = value => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const cleanDate = value => value ? new Date(`${value}T12:00:00`).toLocaleDateString("en-CA", {month:"short",day:"numeric",year:"numeric"}) : "Not set";
  const isoToday = () => new Date().toISOString().slice(0,10);
  const money = value => new Intl.NumberFormat("en-CA",{style:"currency",currency:"CAD",maximumFractionDigits:0}).format(Number(value||0));
  const statuses = ["New Lead","Contacted","Replied","Interested","Free Beat Sent","Negotiating","Client","Returning Client","Inactive"];
  const relationships = ["Cold","Warm","Hot Lead","Client","VIP"];
  const DRAFT_KEY = "statusos_artist_activity_drafts_v1";
  let saveTimer = null;
  function readDrafts(){ try{return JSON.parse(localStorage.getItem(DRAFT_KEY)||"{}");}catch{return {};} }
  function getDraft(id){ return readDrafts()[id]||{}; }
  function setDraft(id,draft){ const all=readDrafts(); all[id]=draft; localStorage.setItem(DRAFT_KEY,JSON.stringify(all)); }
  function clearDraft(id){ const all=readDrafts(); delete all[id]; localStorage.setItem(DRAFT_KEY,JSON.stringify(all)); }
  function schedulePersist(artist){ clearTimeout(saveTimer); saveTimer=setTimeout(()=>persistArtist(artist),700); }
  function normalizeArtist(artist) {
    artist.email ||= ""; artist.phone ||= ""; artist.website ||= ""; artist.location ||= "";
    artist.status ||= "New Lead"; artist.relationship ||= "Warm"; artist.notes ||= "";
    artist.tags = Array.isArray(artist.tags) ? artist.tags : [];
    artist.revenue = Number(artist.revenue||0);
    artist.createdAt ||= new Date().toISOString(); artist.updatedAt ||= artist.createdAt;
    artist.activities = Array.isArray(artist.activities) ? artist.activities : [];
    artist.songs = Array.isArray(artist.songs) ? artist.songs : [];
    artist.beats = Array.isArray(artist.beats) ? artist.beats : [];
    return artist;
  }
  const repo=()=>window.StatusOS?.ArtistRepository;
  function all(){const rows=repo()?.list?.()||window.state?.artists||[];rows.forEach(normalizeArtist);if(window.state)state.artists=rows;return rows;}
  function selected(){return all().find(a=>a.id===selectedArtistId);}
  function persistArtist(artist){repo()?.save?.(artist);if(window.state)state.artists=repo()?.list?.()||state.artists;window.dispatchEvent(new CustomEvent("statusos:artists-updated"));render();}
  function addActivity(artist,type,title,details,date){artist.activities.unshift({id:uid(),type,title,details:details||"",date:date||isoToday(),createdAt:new Date().toISOString()});artist.lastContact=["DM Sent","Email Sent","Follow-up","Reply Received","Beat Sent","Call"].includes(type)?(date||isoToday()):artist.lastContact;artist.updatedAt=new Date().toISOString();}
  function linkedTasks(a){return (window.state?.tasks||[]).filter(t=>String(t.artist||"").toLowerCase()===String(a.name||"").toLowerCase());}
  function linkedProjects(a){return (window.state?.projects||[]).filter(p=>String(p.artist||p.client||"").toLowerCase()===String(a.name||"").toLowerCase());}
  function renderStats(){const artists=all(),today=isoToday();const due=artists.filter(a=>a.followUp&&a.followUp<=today&&!['Inactive'].includes(a.status)).length;const hot=artists.filter(a=>a.relationship==='Hot Lead'||['Interested','Negotiating'].includes(a.status)).length;const clients=artists.filter(a=>['Client','Returning Client'].includes(a.status)).length;const revenue=artists.reduce((n,a)=>n+Number(a.revenue||0),0);[["artistTotalCount",artists.length],["artistContactedCount",hot],["artistInterestedCount",clients],["artistFollowupCount",due]].forEach(([id,v])=>{const el=document.getElementById(id);if(el)el.textContent=v;});const labels={artistContactedLabel:'Hot Leads',artistInterestedLabel:'Clients'};Object.entries(labels).forEach(([id,v])=>{const el=document.getElementById(id);if(el)el.textContent=v;});const revenueEl=document.getElementById('artistRevenueTotal');if(revenueEl)revenueEl.textContent=money(revenue);}
  function filteredArtists(){const q=(document.getElementById('crmSearch')?.value||'').toLowerCase(),f=document.getElementById('crmFilter')?.value||'';return all().filter(a=>!f||a.status===f).filter(a=>!q||JSON.stringify(a).toLowerCase().includes(q)).sort((a,b)=>{const ad=a.followUp&&a.followUp<=isoToday()?0:1,bd=b.followUp&&b.followUp<=isoToday()?0:1;return ad-bd||String(b.updatedAt).localeCompare(String(a.updatedAt));});}
  function renderDirectory(){const artists=filteredArtists(),box=document.getElementById('artistDirectory'),empty=document.getElementById('artistEmptyState');if(!box)return;document.getElementById('artistDirectoryCount').textContent=`${artists.length} artist${artists.length===1?'':'s'}`;empty?.classList.toggle('hidden',artists.length>0);box.innerHTML=artists.map(a=>{const due=a.followUp&&a.followUp<=isoToday()&&a.status!=='Inactive';return `<button class="artist-directory-item ${a.id===selectedArtistId?'active':''}" data-artist-id="${a.id}"><span class="artist-avatar">${esc((a.name||'?').slice(0,1).toUpperCase())}</span><span class="artist-directory-main"><strong>${esc(a.name)}</strong><small>${esc(a.contact||a.email||a.genre||'No contact added')}</small><span class="artist-chip-row"><span class="artist-status-chip">${esc(a.status)}</span><span class="artist-status-chip relationship-${esc(a.relationship.toLowerCase().replace(/\s/g,'-'))}">${esc(a.relationship)}</span></span></span><span class="artist-directory-meta">${due?'<b class="followup-due">Follow up</b>':`<small>${esc(a.followUp?cleanDate(a.followUp):'No follow-up')}</small>`}</span></button>`}).join('');box.querySelectorAll('[data-artist-id]').forEach(btn=>btn.addEventListener('click',()=>{selectedArtistId=btn.dataset.artistId;window.StatusOS?.Workspace?.saveSelectedArtist?.(selectedArtistId);document.getElementById('crm')?.classList.add('crm-profile-open');render();window.scrollTo({top:0,behavior:'smooth'});}));}
  function activityIcon(type){return ({"Song Researched":"♫","DM Sent":"↗","Email Sent":"✉","Reply Received":"💬","Beat Sent":"◆","Follow-up":"↻","Note":"•","Call":"☎","Payment":"$","Project Started":"▣"})[type]||'•';}
  function renderWorkspace(){const a=selected(),empty=document.getElementById('artistWorkspaceEmpty'),content=document.getElementById('artistWorkspaceContent');if(!content)return;empty?.classList.toggle('hidden',!!a);content.classList.toggle('hidden',!a);if(!a)return;const draft=getDraft(a.id),timeline=[...a.activities].filter(x=>!x.deletedAt).sort((x,y)=>String(y.date).localeCompare(String(x.date))||String(y.createdAt).localeCompare(String(x.createdAt)));const tasks=linkedTasks(a),projects=linkedProjects(a),openTasks=tasks.filter(t=>!t.done&&t.status!=='Completed');content.innerHTML=`
  <button class="mini-btn artist-mobile-back" id="artistBackBtn" type="button">‹ All Artists</button><div class="artist-profile-head"><div class="artist-profile-identity"><span class="artist-avatar large">${esc(a.name.slice(0,1).toUpperCase())}</span><div><p class="eyebrow">ARTIST PROFILE</p><h2>${esc(a.name)}</h2><p class="muted">${esc([a.contact,a.genre,a.location].filter(Boolean).join(' · ')||'Add contact details')}</p><div class="artist-profile-badges"><span class="artist-status-chip">${esc(a.status)}</span><span class="artist-status-chip">${esc(a.relationship)}</span>${a.tags.map(t=>`<span class="artist-status-chip">${esc(t)}</span>`).join('')}</div></div></div><div class="artist-profile-actions"><button class="mini-btn" id="quickFollowupBtn">Log Follow-up</button><button class="mini-btn delete" id="deleteArtistBtn">Delete</button></div></div>
  <div class="artist-kpi-grid"><div><span>Revenue</span><strong>${money(a.revenue)}</strong></div><div><span>Beats Sent</span><strong>${a.activities.filter(x=>!x.deletedAt&&x.type==='Beat Sent').length}</strong></div><div><span>Replies</span><strong>${a.activities.filter(x=>!x.deletedAt&&x.type==='Reply Received').length}</strong></div><div><span>Open Tasks</span><strong>${openTasks.length}</strong></div><div><span>Projects</span><strong>${projects.length}</strong></div></div>
  <details class="crm-profile-details"><summary>Contact and profile details</summary><div class="artist-profile-controls crm-expanded-controls"><label>Pipeline<select id="artistStatusSelect">${statuses.map(x=>`<option ${a.status===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Relationship<select id="artistRelationshipInput">${relationships.map(x=>`<option ${a.relationship===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Next Follow-up<input id="artistFollowupInput" type="date" value="${esc(a.followUp||'')}"></label><label>Instagram<input id="artistContactInput" value="${esc(a.contact||'')}" placeholder="@handle"></label><label>Email<input id="artistEmailInput" type="email" value="${esc(a.email||'')}" placeholder="artist@email.com"></label><label>Phone<input id="artistPhoneInput" value="${esc(a.phone||'')}" placeholder="Phone"></label><label>Location<input id="artistLocationInput" value="${esc(a.location||'')}" placeholder="City"></label><label>Website<input id="artistWebsiteInput" value="${esc(a.website||'')}" placeholder="https://"></label><label>Revenue (CAD)<input id="artistRevenueInput" type="number" min="0" step="1" value="${esc(a.revenue||0)}"></label><label>Tags<input id="artistTagsInput" value="${esc(a.tags.join(', '))}" placeholder="West Coast, VIP"></label></div></details>
  <div class="artist-workspace-grid"><section><div class="section-head"><div><p class="eyebrow">ACTIVITY</p><h3>Relationship Timeline</h3></div></div><form id="artistActivityForm" class="artist-activity-form"><select name="type">${['Song Researched','DM Sent','Email Sent','Reply Received','Beat Sent','Follow-up','Call','Payment','Project Started','Note'].map(x=>`<option ${draft.type===x?'selected':''}>${x}</option>`).join('')}</select><input name="title" required placeholder="What happened?" value="${esc(draft.title||'')}"><input name="details" placeholder="Beat, subject, amount or notes" value="${esc(draft.details||'')}"><input name="date" type="date" value="${esc(draft.date||isoToday())}"><button class="button" type="submit">Log</button></form><div class="artist-timeline">${timeline.length?timeline.map(x=>`<article class="artist-timeline-item"><span class="artist-timeline-icon">${activityIcon(x.type)}</span><div><div class="artist-timeline-title"><strong>${esc(x.title)}</strong><small>${esc(cleanDate(x.date))}</small></div><span class="artist-status-chip">${esc(x.type)}</span>${x.details?`<p>${esc(x.details)}</p>`:''}</div><button class="timeline-delete" data-delete-activity="${x.id}" title="Delete">×</button></article>`).join(''):'<div class="mission-v2-empty">No activity yet. Log your first contact, beat sent, reply, or note.</div>'}</div></section>
  <aside><div class="artist-notes-panel"><p class="eyebrow">RELATIONSHIP NOTES</p><h3>Sound, preferences and context</h3><textarea id="artistNotesInput" rows="7" placeholder="Song references, beat preferences, lyrical style, personal details...">${esc(a.notes||'')}</textarea><button id="saveArtistNotesBtn" class="button secondary" type="button">Save Notes</button></div><div class="artist-linked-panel"><p class="eyebrow">CONNECTED WORK</p><h3>Tasks and projects</h3>${openTasks.length?openTasks.slice(0,5).map(t=>`<div class="artist-linked-row"><span>Task</span><strong>${esc(t.title||'Untitled')}</strong></div>`).join(''):'<p class="muted small">No open linked tasks.</p>'}${projects.length?projects.slice(0,5).map(p=>`<div class="artist-linked-row"><span>Project</span><strong>${esc(p.name||p.title||'Untitled')}</strong></div>`).join(''):'<p class="muted small">No linked projects.</p>'}</div></aside></div>`;bindWorkspace(a);}
  function bindField(id,key,transform=v=>v){document.getElementById(id)?.addEventListener('change',e=>{const a=selected();if(!a)return;a[key]=transform(e.target.value);a.updatedAt=new Date().toISOString();persistArtist(a);});}
  function bindWorkspace(a){document.getElementById('artistBackBtn')?.addEventListener('click',()=>{document.getElementById('crm')?.classList.remove('crm-profile-open');});bindField('artistStatusSelect','status');bindField('artistRelationshipInput','relationship');bindField('artistFollowupInput','followUp');['artistContactInput','artistEmailInput','artistPhoneInput','artistLocationInput','artistWebsiteInput'].forEach(id=>{const key=id.replace('artist','').replace('Input','');const real=key.charAt(0).toLowerCase()+key.slice(1);document.getElementById(id)?.addEventListener('input',e=>{a[real]=e.target.value.trim();a.updatedAt=new Date().toISOString();schedulePersist(a);});});bindField('artistRevenueInput','revenue',v=>Number(v||0));bindField('artistTagsInput','tags',v=>v.split(',').map(x=>x.trim()).filter(Boolean));document.getElementById('artistNotesInput')?.addEventListener('input',e=>{a.notes=e.target.value;a.updatedAt=new Date().toISOString();clearTimeout(saveTimer);saveTimer=setTimeout(()=>persistArtist(a),700);});document.getElementById('saveArtistNotesBtn')?.addEventListener('click',()=>{a.notes=document.getElementById('artistNotesInput').value.trim();persistArtist(a);});const form=document.getElementById('artistActivityForm');form?.addEventListener('input',()=>setDraft(a.id,Object.fromEntries(new FormData(form))));form?.addEventListener('change',()=>setDraft(a.id,Object.fromEntries(new FormData(form))));form?.addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));addActivity(a,d.type,d.title,d.details,d.date);clearDraft(a.id);if(d.type==='Reply Received'&&['New Lead','Contacted'].includes(a.status))a.status='Replied';if(d.type==='Beat Sent')a.status='Free Beat Sent';if(d.type==='Payment'){const amount=Number(String(d.details).replace(/[^0-9.]/g,''));if(amount)a.revenue+=amount;}persistArtist(a);});document.getElementById('quickFollowupBtn')?.addEventListener('click',()=>{addActivity(a,'Follow-up','Follow-up completed','',isoToday());a.followUp='';persistArtist(a);});document.querySelectorAll('[data-delete-activity]').forEach(btn=>btn.addEventListener('click',()=>{repo()?.deleteActivity?.(a.id,btn.dataset.deleteActivity);if(window.state)state.artists=repo()?.list?.()||state.artists;render();}));document.getElementById('deleteArtistBtn')?.addEventListener('click',()=>{if(confirm(`Move ${a.name} to the Recycle Bin?`)){repo()?.softDelete?.(a.id);selectedArtistId=null;window.StatusOS?.Workspace?.saveSelectedArtist?.(null);if(window.state)state.artists=repo()?.list?.()||[];render();}});}
  function bindAddForm(){const form=document.getElementById('artistForm');if(!form||form.dataset.artistOsBound)return;form.dataset.artistOsBound='1';form.addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();e.stopImmediatePropagation();const d=Object.fromEntries(new FormData(form));d.tags=String(d.tags||'').split(',').map(x=>x.trim()).filter(Boolean);d.revenue=Number(d.revenue||0);const a=normalizeArtist({id:uid(),...d,lastContact:d.status==='New Lead'?'':isoToday()});if(d.notes)addActivity(a,'Note','Artist added',d.notes,isoToday());repo()?.save?.(a);if(window.state)state.artists=repo()?.list?.()||[];selectedArtistId=a.id;window.StatusOS?.Workspace?.saveSelectedArtist?.(selectedArtistId);form.reset();form.closest('dialog')?.close();render();},true);}
  function render(){renderStats();renderDirectory();renderWorkspace();}
  async function init(){await repo()?.init?.();all();bindAddForm();document.getElementById('crmSearch')?.addEventListener('input',render);document.getElementById('crmFilter')?.addEventListener('change',render);const savedId=window.StatusOS?.Workspace?.getSelectedArtist?.();if(savedId&&all().some(a=>a.id===savedId))selectedArtistId=savedId;if(!selectedArtistId&&all().length&&innerWidth>760)selectedArtistId=all()[0].id;window.StatusOS?.Workspace?.saveSelectedArtist?.(selectedArtistId);render();}
  window.addEventListener('DOMContentLoaded',init);window.addEventListener('statusos:view-change',e=>{if(e.detail?.view==='crm'||document.getElementById('crm')?.classList.contains('active'))render();});window.addEventListener('statusos:workspace-restore',e=>{const id=e.detail?.selectedArtistId;if(id&&all().some(a=>a.id===id)){selectedArtistId=id;render();}});window.StatusOS=window.StatusOS||{};window.StatusOS.ArtistOS={render,list:all};window.addEventListener('statusos:artists-updated',()=>{if(window.state)state.artists=repo()?.list?.()||[];render();});
})();
