(function(){
  const $=id=>document.getElementById(id);
  const cash=v=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD',maximumFractionDigits:0}).format(Number(v||0));
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const uid=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random());
  const iso=()=>new Date().toISOString().slice(0,10);
  let active='overview';
  function ensure(){ if(!Array.isArray(state.expenses))state.expenses=[]; if(!Array.isArray(state.invoices))state.invoices=[]; }
  function monthKey(d){return String(d||'').slice(0,7)}
  function currentMonth(){return iso().slice(0,7)}
  function totals(){
    ensure(); const month=currentMonth();
    const monthRevenue=state.revenue.filter(x=>monthKey(x.date)===month).reduce((n,x)=>n+Number(x.amount||0),0);
    const monthExpenses=state.expenses.filter(x=>monthKey(x.date)===month).reduce((n,x)=>n+Number(x.amount||0),0);
    const projectOutstanding=state.projects.reduce((n,p)=>n+Math.max(0,Number(p.budget||p.price||0)-Number(p.paid||0)),0);
    const invoiceOutstanding=state.invoices.filter(i=>!['Paid'].includes(i.status)).reduce((n,i)=>n+Math.max(0,Number(i.amount||0)-Number(i.paid||0)),0);
    return {monthRevenue,monthExpenses,profit:monthRevenue-monthExpenses,outstanding:projectOutstanding+invoiceOutstanding,projectOutstanding,invoiceOutstanding};
  }
  function set(id,v){const n=$(id);if(n)n.textContent=v}
  function renderSummary(){const t=totals();set('financeMonthRevenue',cash(t.monthRevenue));set('financeMonthExpenses',cash(t.monthExpenses));set('financeMonthProfit',cash(t.profit));set('financeOutstanding',cash(t.outstanding));}
  function renderIncome(){const el=$('revenueTable');if(!el)return;el.innerHTML=[...state.revenue].sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(x=>`<tr><td>${esc(x.date||'')}</td><td>${esc(x.source||'Income')}</td><td>${esc(x.name||'—')}</td><td><strong>${cash(x.amount)}</strong></td><td><button class="mini-btn delete" data-finance-delete="income" data-id="${x.id}">Delete</button></td></tr>`).join('')||'<tr><td colspan="5" class="muted">No income recorded.</td></tr>';}
  function renderExpenses(){const el=$('expenseTable');if(!el)return;el.innerHTML=[...state.expenses].sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(x=>`<tr><td>${esc(x.date||'')}</td><td>${esc(x.category||'Other')}</td><td>${esc(x.description||'—')}</td><td><strong>${cash(x.amount)}</strong></td><td><button class="mini-btn delete" data-finance-delete="expense" data-id="${x.id}">Delete</button></td></tr>`).join('')||'<tr><td colspan="5" class="muted">No expenses recorded.</td></tr>';}
  function invoiceStatus(i){if(i.status==='Paid')return'Paid';if(i.dueDate&&i.dueDate<iso())return'Overdue';return i.status||'Draft'}
  function renderInvoices(){const el=$('invoiceList');if(!el)return;el.innerHTML=[...state.invoices].sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).map(i=>{const s=invoiceStatus(i);return`<article class="card finance-item-card"><div><span class="status-pill ${s==='Overdue'?'danger':''}">${esc(s)}</span><h3>${esc(i.client)}</h3><p>${esc(i.description)}</p><small>${esc(i.project||'No linked project')} • Due ${esc(i.dueDate||'—')}</small></div><div class="finance-item-money"><strong>${cash(i.amount)}</strong>${s!=='Paid'?`<button class="mini-btn" data-invoice-paid="${i.id}">Mark Paid</button>`:''}<button class="mini-btn delete" data-finance-delete="invoice" data-id="${i.id}">Delete</button></div></article>`}).join('')||'<article class="card empty-state"><p>No invoices yet.</p></article>';}
  function clientRows(){const map=new Map();state.projects.forEach(p=>{const name=(p.artist||p.client||'Independent').trim()||'Independent';const r=map.get(name)||{name,paid:0,outstanding:0,projects:0};r.projects++;r.paid+=Number(p.paid||0);r.outstanding+=Math.max(0,Number(p.budget||p.price||0)-Number(p.paid||0));map.set(name,r)});state.revenue.forEach(x=>{const name=(x.name||'').trim();if(!name)return;const r=map.get(name)||{name,paid:0,outstanding:0,projects:0};r.paid+=Number(x.amount||0);map.set(name,r)});return [...map.values()].sort((a,b)=>(b.paid+b.outstanding)-(a.paid+a.outstanding));}
  function renderClients(){const el=$('clientBalanceList');if(!el)return;el.innerHTML=clientRows().map(c=>`<article class="card finance-item-card"><div><h3>${esc(c.name)}</h3><p>${c.projects} linked project${c.projects===1?'':'s'}</p><small>Lifetime tracked: ${cash(c.paid)}</small></div><div class="finance-item-money"><span>Outstanding</span><strong>${cash(c.outstanding)}</strong></div></article>`).join('')||'<article class="card empty-state"><p>No client finance records yet.</p></article>';}
  function lastMonths(){const arr=[];const now=new Date();for(let i=5;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1);arr.push({key:d.toISOString().slice(0,7),label:d.toLocaleDateString('en-CA',{month:'short'})})}return arr}
  function renderOverview(){const months=lastMonths().map(m=>({...m,income:state.revenue.filter(x=>monthKey(x.date)===m.key).reduce((n,x)=>n+Number(x.amount||0),0),expense:state.expenses.filter(x=>monthKey(x.date)===m.key).reduce((n,x)=>n+Number(x.amount||0),0)}));const max=Math.max(1,...months.flatMap(x=>[x.income,x.expense]));const bars=$('financeCashFlow');if(bars)bars.innerHTML=months.map(m=>`<div class="finance-bar-month"><div class="finance-bar-pair"><i class="income" style="height:${Math.max(3,m.income/max*100)}%" title="Income ${cash(m.income)}"></i><i class="expense" style="height:${Math.max(3,m.expense/max*100)}%" title="Expenses ${cash(m.expense)}"></i></div><span>${m.label}</span></div>`).join('');const services={};state.revenue.forEach(x=>services[x.source||'Other']=(services[x.source||'Other']||0)+Number(x.amount||0));const service=$('financeServiceMix');if(service)service.innerHTML=Object.entries(services).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([k,v])=>`<div class="finance-list-row"><span>${esc(k)}</span><strong>${cash(v)}</strong></div>`).join('')||'<p class="muted">Add income to see your service mix.</p>';const attention=$('financeAttention');if(attention){const overdue=state.invoices.filter(i=>invoiceStatus(i)==='Overdue');const balances=state.projects.filter(p=>Number(p.budget||0)>Number(p.paid||0));attention.innerHTML=[...overdue.map(i=>`<div class="finance-list-row warning"><span>Overdue invoice • ${esc(i.client)}</span><strong>${cash(i.amount)}</strong></div>`),...balances.slice(0,5).map(p=>`<div class="finance-list-row"><span>${esc(p.name)} • balance remaining</span><strong>${cash(Number(p.budget||0)-Number(p.paid||0))}</strong></div>`)].join('')||'<p class="muted">Nothing needs attention right now.</p>';}}
  function renderReport(){const el=$('financeReportSummary');if(!el)return;const t=totals();const allRevenue=state.revenue.reduce((n,x)=>n+Number(x.amount||0),0),allExpenses=state.expenses.reduce((n,x)=>n+Number(x.amount||0),0);el.innerHTML=`<div><span>All-time revenue</span><strong>${cash(allRevenue)}</strong></div><div><span>All-time expenses</span><strong>${cash(allExpenses)}</strong></div><div><span>Tracked profit</span><strong>${cash(allRevenue-allExpenses)}</strong></div><div><span>Open invoices</span><strong>${state.invoices.filter(i=>invoiceStatus(i)!=='Paid').length}</strong></div><div><span>Project balances</span><strong>${cash(t.projectOutstanding)}</strong></div><div><span>Average income entry</span><strong>${cash(state.revenue.length?allRevenue/state.revenue.length:0)}</strong></div>`;}
  function render(){ensure();renderSummary();renderIncome();renderExpenses();renderInvoices();renderClients();renderOverview();renderReport();}
  function saveFinance(){save();render();window.dispatchEvent(new CustomEvent('statusos:finance-updated'));}
  function bind(){document.querySelectorAll('[data-finance-tab]').forEach(b=>b.addEventListener('click',()=>{active=b.dataset.financeTab;document.querySelectorAll('[data-finance-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('[data-finance-panel]').forEach(x=>x.classList.toggle('hidden',x.dataset.financePanel!==active));}));const ef=$('expenseForm');if(ef)ef.addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(ef));state.expenses.push({id:uid(),...d,amount:Number(d.amount||0),createdAt:new Date().toISOString()});ef.closest('dialog').close();ef.reset();saveFinance()});const inf=$('invoiceForm');if(inf)inf.addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(inf));state.invoices.push({id:uid(),...d,amount:Number(d.amount||0),paid:0,createdAt:new Date().toISOString()});inf.closest('dialog').close();inf.reset();saveFinance()});document.addEventListener('click',e=>{const del=e.target.closest('[data-finance-delete]');if(del){const key=del.dataset.financeDelete==='income'?'revenue':del.dataset.financeDelete==='expense'?'expenses':'invoices';state[key]=state[key].filter(x=>x.id!==del.dataset.id);saveFinance();return}const paid=e.target.closest('[data-invoice-paid]');if(paid){const i=state.invoices.find(x=>x.id===paid.dataset.invoicePaid);if(i){i.status='Paid';i.paid=Number(i.amount||0);i.paidDate=iso();state.revenue.push({id:uid(),date:iso(),source:'Invoice Payment',name:i.client,amount:Number(i.amount||0),invoiceId:i.id});saveFinance()}}});const exportBtn=$('exportFinanceCsv');if(exportBtn)exportBtn.addEventListener('click',exportCsv);['expenseModal','invoiceModal','revenueModal'].forEach(id=>{const d=$(id);if(d)d.addEventListener('toggle',()=>{const dateInput=d.querySelector('input[name="date"]');if(dateInput&&!dateInput.value)dateInput.value=iso()})});window.addEventListener('statusos:projects-updated',render);}
  function exportCsv(){const rows=[['Type','Date','Category/Source','Client/Description','Amount','Status'],...state.revenue.map(x=>['Income',x.date,x.source,x.name,Number(x.amount||0),'Received']),...state.expenses.map(x=>['Expense',x.date,x.category,x.description,-Number(x.amount||0),'Paid']),...state.invoices.map(x=>['Invoice',x.createdAt?.slice(0,10)||'',x.project||'',x.client,Number(x.amount||0),invoiceStatus(x)])];const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`StatusOS-Finance-${iso()}.csv`;a.click();URL.revokeObjectURL(a.href)}
  window.StatusOS=window.StatusOS||{};window.StatusOS.Finance={render,totals,exportCsv};
  document.addEventListener('DOMContentLoaded',()=>{ensure();bind();render()});
})();
