/* StatusOS v3.5.3 Focus Alarm Studio */
(function(){
  'use strict';
  const KEY='statusos_success_os_v2';
  const SETTINGS_KEY='statusos_focus_alarm_settings_v1';
  const CLOUD_TABLE='statusos_success_os';
  const sounds=[
    {id:'statusos',name:'StatusOS Chime',kind:'synth'},
    {id:'classic-ring',name:'Classic Ring',src:'./sounds/classic-ring.wav'},
    {id:'80s-digital',name:'80s Digital Alarm',src:'./sounds/80s-digital-alarm.wav'},
    {id:'tibetan-bell',name:'Tibetan Bell',src:'./sounds/tibetan-bell.wav'},
    {id:'wind-chimes',name:'Wind Chimes',src:'./sounds/wind-chimes.wav'},
    {id:'rooster',name:'Rooster',src:'./sounds/rooster.wav'},
    {id:'pinball-arcade',name:'Pinball Arcade',src:'./sounds/pinball-arcade.wav'}
  ];
  const quotes=[
    ['Challenges are what make life interesting, and overcoming them is what makes life meaningful.','Joshua J. Marine'],
    ['Success is the sum of small efforts, repeated day in and day out.','Robert Collier'],
    ['The secret of getting ahead is getting started.','Mark Twain'],
    ['You do not have to see the whole staircase, just take the first step.','Martin Luther King Jr.'],
    ['What you do today can improve all your tomorrows.','Ralph Marston'],
    ['Great things are done by a series of small things brought together.','Vincent van Gogh'],
    ['Focus on being productive instead of busy.','Tim Ferriss'],
    ['The future depends on what you do today.','Mahatma Gandhi'],
    ['Action is the foundational key to all success.','Pablo Picasso'],
    ['A year from now you may wish you had started today.','Karen Lamb'],
    ['It always seems impossible until it is done.','Nelson Mandela'],
    ['Discipline is choosing between what you want now and what you want most.','Abraham Lincoln']
  ];
  const escapeHtml=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const iso=(d=new Date())=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)};
  let selectedDate=window.StatusOSSuccessDate?.get?.()||iso();
  let duration=25*60,remaining=duration,running=false,endAt=0,ticker=null,mode='focus',audioCtx=null;
  let alarmAudio=null,alarmStopTimer=null,synthAlarmTimer=null,previewTimer=null,cloudPushTimer=null,alarmActive=false;

  function read(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch{return {}}}
  function settings(){try{return {...{sound:'statusos',volume:.8,alarmDuration:'30',soundOn:true,vibrate:true},...(JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')||{})}}catch{return {sound:'statusos',volume:.8,alarmDuration:'30',soundOn:true,vibrate:true}}}
  function saveSettings(next){const merged={...settings(),...next};localStorage.setItem(SETTINGS_KEY,JSON.stringify(merged));return merged}
  function day(){const data=read();data.days ||= {};data.days[selectedDate] ||= {morning:{checks:{}},night:{},planner:{}};const entry=data.days[selectedDate];entry.planner ||= {};const p=entry.planner;p.tasks ||= Array.from({length:5},()=>({text:'',target:1,actual:0}));while(p.tasks.length<5)p.tasks.push({text:'',target:1,actual:0});p.stats ||= {sessions:0,focusMinutes:0,breakMinutes:0,focusSeconds:0,breakSeconds:0};return {data,entry,p}}
  function save(mutator){const {data,entry,p}=day();mutator(p);entry.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(data));window.dispatchEvent(new CustomEvent('statusos:success-updated'));scheduleCloudPush();renderPlanner()}
  async function cloudContext(){const sb=window.statusOSSupabase;if(!sb||!navigator.onLine)return null;const {data:{user},error}=await sb.auth.getUser();if(error||!user)return null;return {sb,user}}
  async function cloudPush(){const ctx=await cloudContext();if(!ctx)return;try{const data=read();const rows=Object.entries(data.days||{}).map(([entry_date,payload])=>({user_id:ctx.user.id,entry_date,payload,updated_at:payload.updatedAt||new Date().toISOString()}));if(rows.length){const {error}=await ctx.sb.from(CLOUD_TABLE).upsert(rows,{onConflict:'user_id,entry_date'});if(error)throw error;}window.dispatchEvent(new CustomEvent('statusos:focus-sync',{detail:{status:'synced'}}));}catch(error){console.warn('Focus Planner cloud push failed',error);window.dispatchEvent(new CustomEvent('statusos:focus-sync',{detail:{status:'pending',error}}));}}
  function scheduleCloudPush(){clearTimeout(cloudPushTimer);cloudPushTimer=setTimeout(cloudPush,500)}
  async function cloudPull(){const ctx=await cloudContext();if(!ctx)return;try{const {data:rows,error}=await ctx.sb.from(CLOUD_TABLE).select('entry_date,payload,updated_at').eq('user_id',ctx.user.id);if(error)throw error;const local=read();local.days ||= {};for(const row of rows||[]){const current=local.days[row.entry_date];const localTime=current?.updatedAt||'';const cloudTime=row.updated_at||row.payload?.updatedAt||'';if(!current||!localTime||new Date(cloudTime)>=new Date(localTime)){local.days[row.entry_date]={...(row.payload||{}),updatedAt:cloudTime||new Date().toISOString()};}}localStorage.setItem(KEY,JSON.stringify(local));renderPlanner();window.dispatchEvent(new CustomEvent('statusos:success-updated'));window.dispatchEvent(new CustomEvent('statusos:focus-sync',{detail:{status:'synced'}}));}catch(error){console.warn('Focus Planner cloud pull failed',error);window.dispatchEvent(new CustomEvent('statusos:focus-sync',{detail:{status:'pending',error}}));}}
  function quoteForDate(){const n=selectedDate.replaceAll('-','').split('').reduce((a,b)=>a+Number(b),0);return quotes[n%quotes.length]}
  function taskMarkup(task,index){const bubbles=Array.from({length:5},(_,i)=>`<button type="button" class="focus-bubble ${i<Math.min(task.actual||0,5)?'filled':''}" data-bubble="${i+1}" aria-label="Set ${i+1} completed Pomodoros"></button>`).join('');return `<div class="focus-task-main"><span>${index+1}.</span><input class="focus-task-input" value="${escapeHtml(task.text)}" placeholder="Enter task..."></div><div class="focus-task-tracking"><label>Target <input class="focus-target-input" type="number" min="1" max="12" value="${Math.max(1,Number(task.target)||1)}"></label><div class="focus-bubbles" aria-label="Completed Pomodoros">${bubbles}</div><span class="focus-actual">${Number(task.actual)||0} actual</span><button type="button" class="focus-use-timer">Use timer</button></div>`}
  function focusSecondsForPlanner(p){if(Number.isFinite(Number(p?.stats?.focusSeconds))&&Number(p.stats.focusSeconds)>0)return Number(p.stats.focusSeconds);return Math.max(0,Number(p?.stats?.focusMinutes)||0)*60}
  function breakSecondsForPlanner(p){if(Number.isFinite(Number(p?.stats?.breakSeconds))&&Number(p.stats.breakSeconds)>0)return Number(p.stats.breakSeconds);return Math.max(0,Number(p?.stats?.breakMinutes)||0)*60}
  function formatTime(seconds){seconds=Math.max(0,Math.round(seconds||0));if(seconds<60)return `${seconds} sec`;const mins=Math.round(seconds/60);if(mins<60)return `${mins} min`;const h=Math.floor(mins/60),m=mins%60;return m?`${h}h ${m}m`:`${h}h`}
  function aggregateStats(){const data=read(),today=iso(),todayDate=new Date(`${today}T12:00:00`),weekStart=new Date(todayDate);weekStart.setDate(todayDate.getDate()-((todayDate.getDay()+6)%7));const month=today.slice(0,7),year=today.slice(0,4);let week=0,monthTotal=0,yearTotal=0,best=0,streak=0;const focusByDay={};for(const [date,entry] of Object.entries(data.days||{})){const sec=focusSecondsForPlanner(entry?.planner);focusByDay[date]=sec;if(date>=iso(weekStart)&&date<=today)week+=sec;if(date.startsWith(month))monthTotal+=sec;if(date.startsWith(year))yearTotal+=sec;best=Math.max(best,sec)}for(let i=0;i<366;i++){const d=new Date(todayDate);d.setDate(todayDate.getDate()-i);if((focusByDay[iso(d)]||0)>0)streak++;else if(i===0)continue;else break}return {week,month:monthTotal,year:yearTotal,best,streak}}
  function renderSoundOptions(){const wrap=document.getElementById('pomodoroSoundOptions');if(!wrap)return;const s=settings();wrap.innerHTML=sounds.map(sound=>`<div class="focus-sound-option ${s.sound===sound.id?'selected':''}"><label><input type="radio" name="pomodoroSound" value="${sound.id}" ${s.sound===sound.id?'checked':''}><span>${escapeHtml(sound.name)}</span></label><button class="focus-sound-preview" type="button" data-preview-sound="${sound.id}">▶ Preview</button></div>`).join('')}
  function renderPlanner(){
    const {p}=day();const [q,a]=quoteForDate();const qt=document.getElementById('focusQuoteText'),qa=document.getElementById('focusQuoteAuthor');if(qt)qt.textContent=q;if(qa)qa.textContent=a;
    p.tasks.forEach((t,i)=>{const row=document.querySelector(`[data-focus-task="${i}"]`);if(row&&!(row.contains(document.activeElement)&&document.activeElement?.matches('input,textarea')))row.innerHTML=taskMarkup(t,i);else if(row&&!row.innerHTML)row.innerHTML=taskMarkup(t,i)});
    const notes=document.getElementById('focusPlannerNotes');if(notes&&document.activeElement!==notes)notes.value=p.notes||'';const reflection=document.getElementById('focusScoreReflection');if(reflection&&document.activeElement!==reflection)reflection.value=p.reflection||'';
    const scores=document.getElementById('focusScoreButtons');if(scores)scores.innerHTML=Array.from({length:10},(_,i)=>`<button type="button" class="${Number(p.score)===i+1?'active':''}" data-score="${i+1}">${i+1}</button>`).join('');
    const select=document.getElementById('pomodoroTaskSelect');if(select){const old=select.value;select.innerHTML='<option value="">No task selected</option>'+p.tasks.map((t,i)=>`<option value="${i}">${i+1}. ${escapeHtml(t.text||'Untitled task')}</option>`).join('');if([...select.options].some(o=>o.value===old))select.value=old}
    const agg=aggregateStats(),focusSec=focusSecondsForPlanner(p),breakSec=breakSecondsForPlanner(p);
    const set=(id,val)=>{const el=document.getElementById(id);if(el)el.textContent=val};set('pomodoroSessionCount',String(p.stats.sessions||0));set('pomodoroFocusTime',formatTime(focusSec));set('pomodoroBreakTime',formatTime(breakSec));set('pomodoroWeekTime',formatTime(agg.week));set('pomodoroMonthTime',formatTime(agg.month));set('pomodoroYearTime',formatTime(agg.year));set('pomodoroFocusStreak',`${agg.streak} day${agg.streak===1?'':'s'}`);set('pomodoroBestDay',formatTime(agg.best));
    const s=settings();const chime=document.getElementById('pomodoroChime'),vibrate=document.getElementById('pomodoroVibrate'),vol=document.getElementById('pomodoroVolume'),alarmDuration=document.getElementById('pomodoroAlarmDuration');if(chime)chime.checked=s.soundOn!==false;if(vibrate)vibrate.checked=s.vibrate!==false;if(vol)vol.value=Math.round((s.volume??.8)*100);if(alarmDuration)alarmDuration.value=String(s.alarmDuration||'30');set('pomodoroVolumeValue',`${Math.round((s.volume??.8)*100)}%`);
    renderSoundOptions();updateTaskLabel();updateTimerUI()
  }
  function updateTaskLabel(){const s=document.getElementById('pomodoroTaskSelect'),label=document.getElementById('pomodoroTaskLabel');if(!label)return;label.textContent=s?.value===''||!s?'No task selected':s.options[s.selectedIndex]?.text||'Selected task'}
  function fmt(sec){return `${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`}
  function updateTimerUI(){if(running)remaining=Math.max(0,Math.ceil((endAt-Date.now())/1000));const d=document.getElementById('pomodoroDisplay');if(d)d.textContent=fmt(remaining);const m=document.getElementById('pomodoroMode');if(m)m.textContent=mode==='focus'?'FOCUS':mode==='short'?'SHORT BREAK':'LONG BREAK';const ring=document.getElementById('pomodoroRing');if(ring){const progress=duration?Math.max(0,Math.min(1,1-remaining/duration)):0;ring.style.setProperty('--timer-progress',`${progress*360}deg`)}const start=document.getElementById('pomodoroStart');if(start)start.textContent=running?'Running…':remaining<duration&&remaining>0?'▶ Continue':'▶ Start';document.title=running?`${fmt(remaining)} • StatusOS`:'StatusOS'}
  function prepareAudio(){try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return null;audioCtx ||= new AC();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}catch{return null}}
  function playSynthOnce(){const ctx=prepareAudio();if(!ctx)return;const now=ctx.currentTime,volume=settings().volume??.8;[659.25,783.99,987.77].forEach((f,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.0001,now+i*.2);g.gain.exponentialRampToValueAtTime(Math.max(.01,.2*volume),now+i*.2+.02);g.gain.exponentialRampToValueAtTime(.0001,now+i*.2+1.4);o.connect(g);g.connect(ctx.destination);o.start(now+i*.2);o.stop(now+i*.2+1.5)})}
  function stopAudioOnly(){clearTimeout(alarmStopTimer);alarmStopTimer=null;clearInterval(synthAlarmTimer);synthAlarmTimer=null;clearTimeout(previewTimer);previewTimer=null;if(alarmAudio){try{alarmAudio.pause();alarmAudio.currentTime=0}catch{}alarmAudio=null}try{navigator.vibrate?.(0)}catch{}}
  function stopAlarm(){stopAudioOnly();alarmActive=false;document.getElementById('pomodoroCompletion')?.classList.add('hidden');document.getElementById('pomodoroRing')?.classList.remove('alarm-ringing');const status=document.getElementById('pomodoroStatus');if(status)status.textContent='Alarm stopped. Choose your next focused block.'}
  function selectedSound(){return sounds.find(x=>x.id===settings().sound)||sounds[0]}
  function beginSound(sound,loop=true){stopAudioOnly();const s=settings();if(s.soundOn===false)return;if(sound.kind==='synth'){playSynthOnce();if(loop)synthAlarmTimer=setInterval(playSynthOnce,2400);return}alarmAudio=new Audio(sound.src);alarmAudio.volume=Math.max(0,Math.min(1,s.volume??.8));alarmAudio.loop=loop;alarmAudio.play().catch(error=>console.warn('Alarm audio could not play',error))}
  function previewSound(id){const sound=sounds.find(x=>x.id===id);if(!sound)return;prepareAudio();beginSound(sound,false);previewTimer=setTimeout(stopAudioOnly,sound.kind==='synth'?2200:6000)}
  function vibrateAlarm(){if(settings().vibrate===false)return;try{navigator.vibrate?.([500,250,500,250,800,250,500,250,500])}catch{}}
  function showCompletion(sessionSeconds){const completion=document.getElementById('pomodoroCompletion');if(!completion)return;const {p}=day();completion.classList.remove('hidden');document.getElementById('pomodoroRing')?.classList.add('alarm-ringing');const title=document.getElementById('pomodoroCompletionTitle'),invested=document.getElementById('pomodoroCompletionMinutes'),total=document.getElementById('pomodoroCompletionTotal');if(title)title.textContent=mode==='focus'?'Focus session complete. Great work.':'Break complete. Ready for the next focused block.';if(invested)invested.textContent=mode==='focus'?`+1 Focus Session • ${formatTime(sessionSeconds)} invested`:`${formatTime(sessionSeconds)} break complete`;if(total)total.textContent=`Today's focus total: ${formatTime(focusSecondsForPlanner(p))}`}
  function startAlarm(){const s=settings();if(s.soundOn===false)return;alarmActive=true;beginSound(selectedSound(),true);vibrateAlarm();const limit=s.alarmDuration==='until-stop'?0:Number(s.alarmDuration||30)*1000;if(limit>0)alarmStopTimer=setTimeout(stopAlarm,limit)}
  function finish(){clearInterval(ticker);ticker=null;running=false;remaining=0;const sessionSeconds=duration;save(p=>{p.stats.sessions=(p.stats.sessions||0)+1;if(mode==='focus'){p.stats.focusSeconds=focusSecondsForPlanner(p)+sessionSeconds;p.stats.focusMinutes=Math.round(p.stats.focusSeconds/60);const index=Number(document.getElementById('pomodoroTaskSelect')?.value);if(Number.isInteger(index)&&index>=0&&p.tasks[index])p.tasks[index].actual=(p.tasks[index].actual||0)+1}else{p.stats.breakSeconds=breakSecondsForPlanner(p)+sessionSeconds;p.stats.breakMinutes=Math.round(p.stats.breakSeconds/60)}});showCompletion(sessionSeconds);startAlarm();const status=document.getElementById('pomodoroStatus');if(status)status.textContent='Timer complete. Press Stop Alarm when you are ready.';updateTimerUI()}
  function tick(){updateTimerUI();if(remaining<=0)finish()}
  function start(){if(running)return;stopAlarm();prepareAudio();if(remaining<=0)remaining=duration;endAt=Date.now()+remaining*1000;running=true;ticker=setInterval(tick,250);const status=document.getElementById('pomodoroStatus');if(status)status.textContent=mode==='focus'?'Focus on one task until the alarm.':'Step away and reset.';updateTimerUI()}
  function pause(){if(!running)return;remaining=Math.max(0,Math.ceil((endAt-Date.now())/1000));running=false;clearInterval(ticker);ticker=null;const status=document.getElementById('pomodoroStatus');if(status)status.textContent='Paused. Continue when ready.';updateTimerUI()}
  function restart(){stopAlarm();running=false;clearInterval(ticker);ticker=null;remaining=duration;const status=document.getElementById('pomodoroStatus');if(status)status.textContent='Timer restarted.';updateTimerUI()}
  function setDurationSeconds(sec){stopAlarm();running=false;clearInterval(ticker);ticker=null;duration=Math.max(1,Math.min(10800,Math.round(Number(sec)||1500)));remaining=duration;document.querySelectorAll('[data-pomodoro-minutes],[data-pomodoro-seconds]').forEach(b=>{const value=b.dataset.pomodoroSeconds?Number(b.dataset.pomodoroSeconds):Number(b.dataset.pomodoroMinutes)*60;b.classList.toggle('active',value===duration)});const mins=document.getElementById('pomodoroCustomMinutes'),seconds=document.getElementById('pomodoroCustomSeconds');if(mins)mins.value=Math.floor(duration/60);if(seconds)seconds.value=duration%60;updateTimerUI()}
  function setMode(next){mode=next;document.querySelectorAll('[data-pomodoro-mode]').forEach(b=>b.classList.toggle('active',b.dataset.pomodoroMode===mode));setDurationSeconds(mode==='focus'?25*60:mode==='short'?5*60:15*60)}
  function bind(){
    document.querySelectorAll('.focus-task-row').forEach(row=>{row.innerHTML=taskMarkup({text:'',target:1,actual:0},Number(row.dataset.focusTask));row.addEventListener('input',e=>{const i=Number(row.dataset.focusTask);if(e.target.matches('.focus-task-input'))save(p=>p.tasks[i].text=e.target.value);if(e.target.matches('.focus-target-input'))save(p=>p.tasks[i].target=Math.max(1,Math.min(12,Number(e.target.value)||1)))});row.addEventListener('click',e=>{const i=Number(row.dataset.focusTask);const bubble=e.target.closest('[data-bubble]');if(bubble)save(p=>{const clicked=Number(bubble.dataset.bubble),current=Number(p.tasks[i].actual)||0;p.tasks[i].actual=current===clicked?clicked-1:clicked});if(e.target.closest('.focus-use-timer')){const s=document.getElementById('pomodoroTaskSelect');if(s){s.value=String(i);updateTaskLabel()}document.querySelector('.pomodoro-panel')?.scrollIntoView({behavior:'smooth',block:'start'})}})});
    document.getElementById('focusPlannerNotes')?.addEventListener('input',e=>save(p=>p.notes=e.target.value));document.getElementById('focusScoreReflection')?.addEventListener('input',e=>save(p=>p.reflection=e.target.value));document.getElementById('focusScoreButtons')?.addEventListener('click',e=>{const b=e.target.closest('[data-score]');if(b)save(p=>p.score=Number(b.dataset.score))});document.getElementById('pomodoroTaskSelect')?.addEventListener('change',updateTaskLabel);
    document.querySelectorAll('[data-pomodoro-minutes]').forEach(b=>b.addEventListener('click',()=>setDurationSeconds(Number(b.dataset.pomodoroMinutes)*60)));document.querySelectorAll('[data-pomodoro-seconds]').forEach(b=>b.addEventListener('click',()=>setDurationSeconds(Number(b.dataset.pomodoroSeconds))));
    document.getElementById('pomodoroCustomBtn')?.addEventListener('click',()=>{const mins=Math.max(0,Number(document.getElementById('pomodoroCustomMinutes')?.value)||0),secs=Math.max(0,Math.min(59,Number(document.getElementById('pomodoroCustomSeconds')?.value)||0));setDurationSeconds(mins*60+secs)});
    document.getElementById('pomodoroStart')?.addEventListener('click',start);document.getElementById('pomodoroPause')?.addEventListener('click',pause);document.getElementById('pomodoroRestart')?.addEventListener('click',restart);document.getElementById('pomodoroStopAlarm')?.addEventListener('click',stopAlarm);document.querySelectorAll('[data-pomodoro-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.pomodoroMode)));
    document.getElementById('pomodoroSoundOptions')?.addEventListener('change',e=>{if(e.target.matches('input[name="pomodoroSound"]')){saveSettings({sound:e.target.value});renderSoundOptions()}});document.getElementById('pomodoroSoundOptions')?.addEventListener('click',e=>{const btn=e.target.closest('[data-preview-sound]');if(btn)previewSound(btn.dataset.previewSound)});
    document.getElementById('pomodoroChime')?.addEventListener('change',e=>{saveSettings({soundOn:e.target.checked});if(!e.target.checked)stopAlarm()});document.getElementById('pomodoroVibrate')?.addEventListener('change',e=>saveSettings({vibrate:e.target.checked}));document.getElementById('pomodoroAlarmDuration')?.addEventListener('change',e=>saveSettings({alarmDuration:e.target.value}));document.getElementById('pomodoroVolume')?.addEventListener('input',e=>{const volume=Math.max(0,Math.min(1,Number(e.target.value)/100));saveSettings({volume});document.getElementById('pomodoroVolumeValue').textContent=`${Math.round(volume*100)}%`;if(alarmAudio)alarmAudio.volume=volume});
    window.addEventListener('statusos:success-date-changed',e=>{selectedDate=e.detail.date;pause();restart();renderPlanner()});window.addEventListener('storage',e=>{if(e.key===KEY||e.key===SETTINGS_KEY)renderPlanner()});window.addEventListener('statusos:app-ready',()=>setTimeout(async()=>{await cloudPull();await cloudPush()},300));window.addEventListener('online',async()=>{await cloudPull();await cloudPush()});document.addEventListener('visibilitychange',async()=>{if(document.visibilityState==='visible'){if(running)tick();await cloudPull();await cloudPush()}});window.addEventListener('beforeunload',stopAudioOnly);
    setTimeout(cloudPull,700);renderPlanner();setDurationSeconds(25*60)
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();
