/* StatusOS v2.3.0 Calendar + Daily Planner */
(function(){
  "use strict";
  const KEY="statusos_planner_items_v1";
  let items=[];
  let selectedDate=new Date().toISOString().slice(0,10);
  const $=id=>document.getElementById(id);
  const uid=()=>crypto.randomUUID?crypto.randomUUID():`plan_${Date.now()}_${Math.random().toString(16).slice(2)}`;
  const notify=(m,t="success")=>window.StatusOS?.Notify?.[t]?.(m)||window.dispatchEvent(new CustomEvent("statusos:notify",{detail:{message:m,type:t}}));
  function load(){try{items=JSON.parse(localStorage.getItem(KEY)||"[]");if(!Array.isArray(items))items=[];}catch{items=[];}}
  function save(){localStorage.setItem(KEY,JSON.stringify(items));render();window.dispatchEvent(new CustomEvent("statusos:planner-updated",{detail:{items:[...items]}}));scheduleCloudPush();}
  function dateLabel(date){return new Intl.DateTimeFormat(undefined,{weekday:"long",month:"long",day:"numeric"}).format(new Date(`${date}T12:00:00`));}
  function weekDates(base){const d=new Date(`${base}T12:00:00`);const day=d.getDay();d.setDate(d.getDate()-day);return Array.from({length:7},(_,i)=>{const x=new Date(d);x.setDate(d.getDate()+i);return x.toISOString().slice(0,10);});}
  function renderWeek(){const host=$("plannerWeekStrip");if(!host)return;host.innerHTML="";weekDates(selectedDate).forEach(date=>{const d=new Date(`${date}T12:00:00`);const count=items.filter(x=>x.date===date&&!x.completed).length;const b=document.createElement("button");b.type="button";b.className=`planner-day${date===selectedDate?" active":""}`;b.innerHTML=`<span>${d.toLocaleDateString(undefined,{weekday:"short"})}</span><strong>${d.getDate()}</strong><small>${count?`${count} item${count===1?"":"s"}`:"Clear"}</small>`;b.onclick=()=>{selectedDate=date;render();};host.appendChild(b);});}
  function render(){const list=$("plannerTimeline");if(!list)return;$("plannerSelectedDate").textContent=dateLabel(selectedDate);const dayItems=items.filter(x=>x.date===selectedDate).sort((a,b)=>(a.time||"99:99").localeCompare(b.time||"99:99"));list.innerHTML="";if(!dayItems.length){list.innerHTML='<div class="planner-empty"><strong>Your day is open.</strong><span>Add a focus block, session, follow-up, workout, or family commitment.</span></div>';}else dayItems.forEach(item=>{const row=document.createElement("article");row.className=`planner-item${item.completed?" completed":""}`;row.innerHTML=`<button class="planner-check" type="button" aria-label="Mark complete">${item.completed?"✓":""}</button><div class="planner-time">${item.time||"Anytime"}</div><div class="planner-copy"><strong></strong><span></span></div><button class="planner-delete" type="button" aria-label="Delete">×</button>`;row.querySelector(".planner-copy strong").textContent=item.title;row.querySelector(".planner-copy span").textContent=item.category||"Plan";row.querySelector(".planner-check").onclick=()=>{item.completed=!item.completed;item.updated_at=new Date().toISOString();save();};row.querySelector(".planner-delete").onclick=()=>{items=items.filter(x=>x.id!==item.id);save();notify("Planner item removed","success");};list.appendChild(row);});
    const open=dayItems.filter(x=>!x.completed).length;$("plannerDayCount").textContent=`${open} open`;
    renderWeek();
  }
  async function cloudPull(){const sb=window.statusOSSupabase;if(!sb)return;try{const {data:{user}}=await sb.auth.getUser();if(!user)return;const {data,error}=await sb.from("planner_items").select("*").eq("user_id",user.id);if(error)throw error;if(Array.isArray(data)){const cloud=data.map(x=>({id:x.id,title:x.title,date:x.plan_date,time:x.plan_time?.slice(0,5)||"",category:x.category,completed:x.completed,updated_at:x.updated_at}));const map=new Map(items.map(x=>[x.id,x]));cloud.forEach(x=>{const local=map.get(x.id);if(!local||new Date(x.updated_at)>=new Date(local.updated_at||0))map.set(x.id,x);});items=[...map.values()];localStorage.setItem(KEY,JSON.stringify(items));render();window.dispatchEvent(new CustomEvent("statusos:planner-updated",{detail:{items:[...items]}}));}}
    catch(e){console.warn("Planner pull failed",e);}
  }
  let pushTimer;
  function scheduleCloudPush(){clearTimeout(pushTimer);pushTimer=setTimeout(cloudPush,500);}
  async function cloudPush(){const sb=window.statusOSSupabase;if(!sb||!navigator.onLine)return;try{const {data:{user}}=await sb.auth.getUser();if(!user)return;const rows=items.map(x=>({id:x.id,user_id:user.id,title:x.title,plan_date:x.date,plan_time:x.time||null,category:x.category||"Plan",completed:!!x.completed,updated_at:x.updated_at||new Date().toISOString()}));if(rows.length){const {error}=await sb.from("planner_items").upsert(rows,{onConflict:"id"});if(error)throw error;}window.dispatchEvent(new CustomEvent("statusos:planner-sync",{detail:{status:"synced"}}));}
    catch(e){console.warn("Planner push failed",e);window.dispatchEvent(new CustomEvent("statusos:planner-sync",{detail:{status:"pending"}}));}
  }
  function bind(){load();const dateInput=$("plannerDate");if(dateInput)dateInput.value=selectedDate;$("plannerPrevWeek")?.addEventListener("click",()=>{const d=new Date(`${selectedDate}T12:00:00`);d.setDate(d.getDate()-7);selectedDate=d.toISOString().slice(0,10);render();});$("plannerNextWeek")?.addEventListener("click",()=>{const d=new Date(`${selectedDate}T12:00:00`);d.setDate(d.getDate()+7);selectedDate=d.toISOString().slice(0,10);render();});$("plannerTodayBtn")?.addEventListener("click",()=>{selectedDate=new Date().toISOString().slice(0,10);render();});$("addPlannerItemBtn")?.addEventListener("click",()=>{const f=$("plannerForm");f.reset();f.elements.date.value=selectedDate;$("plannerModal").showModal();});$("plannerForm")?.addEventListener("submit",e=>{e.preventDefault();const f=e.currentTarget;const fd=new FormData(f);items.push({id:uid(),title:String(fd.get("title")||"").trim(),date:String(fd.get("date")),time:String(fd.get("time")||""),category:String(fd.get("category")||"Plan"),completed:false,updated_at:new Date().toISOString()});save();$("plannerModal").close();notify("Added to your day","success");});window.addEventListener("statusos:app-ready",()=>setTimeout(cloudPull,250));window.addEventListener("online",cloudPush);document.addEventListener("visibilitychange",()=>{if(!document.hidden){cloudPull();cloudPush();}});render();}
  window.StatusOS=window.StatusOS||{};window.StatusOS.Planner={render,pull:cloudPull,push:cloudPush,list:()=>items.map(x=>({...x})),selectedDate:()=>selectedDate,selectDate:(date)=>{selectedDate=date||new Date().toISOString().slice(0,10);render();},add:(input)=>{const item={id:input.id||uid(),title:String(input.title||"Untitled").trim(),date:String(input.date||selectedDate),time:String(input.time||""),category:String(input.category||"Plan"),completed:!!input.completed,updated_at:new Date().toISOString()};items.push(item);save();return item;},addMany:(rows)=>{const created=[];(rows||[]).forEach(input=>{const duplicate=items.some(x=>x.date===(input.date||selectedDate)&&x.title.trim().toLowerCase()===String(input.title||"").trim().toLowerCase());if(!duplicate){const item={id:input.id||uid(),title:String(input.title||"Untitled").trim(),date:String(input.date||selectedDate),time:String(input.time||""),category:String(input.category||"Plan"),completed:false,updated_at:new Date().toISOString()};items.push(item);created.push(item);}});if(created.length)save();return created;}};
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bind,{once:true});else bind();
})();
