/* StatusOS v3.4.0 Daily Reliability */
(function(){
  "use strict";
  const META_KEY="statusos_reliability_meta_v1";
  const PREFIX="statusos_";
  const now=()=>new Date().toISOString();
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  function meta(){try{return JSON.parse(localStorage.getItem(META_KEY)||"{}")}catch{return {}}}
  function setMeta(p){const m={...meta(),...p};localStorage.setItem(META_KEY,JSON.stringify(m));return m}
  function trackedKeys(){return Object.keys(localStorage).filter(k=>k.startsWith(PREFIX)).sort()}
  function payload(){const data={};trackedKeys().forEach(k=>data[k]=localStorage.getItem(k));return {format:"StatusOS Backup",version:window.StatusOS?.Meta?.version||"3.4.0",createdAt:now(),data}}
  function download(){const p=payload();const blob=new Blob([JSON.stringify(p,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`statusos-backup-${p.createdAt.slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);setMeta({lastBackupAt:p.createdAt});render();}
  function restoreFile(file){const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);if(p?.format!=="StatusOS Backup"||!p.data)throw new Error("This is not a StatusOS backup file.");if(!confirm("Restore this backup? Your current StatusOS data will be preserved in an automatic safety snapshot first."))return;localStorage.setItem(`statusos_pre_restore_${Date.now()}`,JSON.stringify(payload()));Object.entries(p.data).forEach(([k,v])=>{if(k.startsWith(PREFIX))localStorage.setItem(k,v)});setMeta({lastRestoreAt:now()});alert("Backup restored. StatusOS will reload now.");location.reload();}catch(e){alert(e.message||"Backup could not be restored.")}};r.readAsText(file)}
  async function syncNow(){const btn=document.getElementById("reliabilitySyncBtn");if(btn){btn.disabled=true;btn.textContent="Syncing…"}try{await window.StatusOS?.Sync?.flushQueue?.();await window.StatusOS?.ArtistRepository?.sync?.();setMeta({lastSyncAt:now(),lastSyncResult:"completed"});}catch(e){setMeta({lastSyncAt:now(),lastSyncResult:"needs attention"});console.warn(e)}finally{render();if(btn){btn.disabled=false;btn.textContent="Sync Now"}}}
  function fmt(x){return x?new Date(x).toLocaleString("en-CA",{dateStyle:"medium",timeStyle:"short"}):"Not yet"}
  function pending(){return (window.StatusOS?.Storage?.getQueue?.().length||0)+(()=>{try{return JSON.parse(localStorage.getItem("statusos_artist_queue_v2")||"[]").length}catch{return 0}})()}
  function render(){const m=meta(),box=document.getElementById("reliabilityCenterBody");if(!box)return;const p=pending();box.innerHTML=`<div class="reliability-metrics"><div><span>Last saved</span><strong>${esc(fmt(m.lastSavedAt))}</strong></div><div><span>Last backup</span><strong>${esc(fmt(m.lastBackupAt))}</strong></div><div><span>Pending sync</span><strong>${p}</strong></div></div><div class="reliability-actions"><button id="reliabilityBackupBtn" class="button" type="button">Create Backup</button><button id="reliabilityRestoreBtn" class="button secondary" type="button">Restore Backup</button><button id="reliabilitySyncBtn" class="button secondary" type="button">Sync Now</button><input id="reliabilityRestoreInput" type="file" accept="application/json,.json" hidden></div><p class="muted small">The backup includes your current artists, activities, habits, projects, planner, tasks, finance records, Success OS data, settings, deleted-item records, and app preferences.</p>`;
    document.getElementById("reliabilityBackupBtn")?.addEventListener("click",download);document.getElementById("reliabilityRestoreBtn")?.addEventListener("click",()=>document.getElementById("reliabilityRestoreInput")?.click());document.getElementById("reliabilityRestoreInput")?.addEventListener("change",e=>{if(e.target.files?.[0])restoreFile(e.target.files[0])});document.getElementById("reliabilitySyncBtn")?.addEventListener("click",syncNow);
    const badge=document.getElementById("globalSaveStatus");if(badge)badge.textContent=p?`${p} change${p===1?"":"s"} pending`:`Saved ${m.lastSavedAt?new Date(m.lastSavedAt).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"}):"locally"}`;
  }
  function inject(){const settings=document.getElementById("settings");if(settings&&!document.getElementById("reliabilityCenter")){const card=document.createElement("article");card.id="reliabilityCenter";card.className="card reliability-center";card.innerHTML='<div class="section-head"><div><p class="eyebrow">DATA PROTECTION</p><h3>Backup & Reliability Center</h3></div><span id="globalSaveStatus" class="status-pill">Saved locally</span></div><div id="reliabilityCenterBody"></div>';settings.prepend(card)}render()}
  const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){const out=original.call(this,k,v);if(this===localStorage&&k!==META_KEY&&String(k).startsWith(PREFIX)){setTimeout(()=>{setMeta({lastSavedAt:now()});render()},0)}return out};
  window.addEventListener("statusos:sync-status",render);window.addEventListener("statusos:artist-sync-status",render);window.addEventListener("online",render);window.addEventListener("offline",render);document.addEventListener("DOMContentLoaded",()=>{setMeta({lastOpenedAt:now()});inject()});
  window.StatusOS=window.StatusOS||{};window.StatusOS.Reliability={backup:download,syncNow,payload};
})();
